version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: meu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha-root
      MYSQL_DATABASE: meu-banco-dados
      MYSQL_USER: meu-usuario
      MYSQL_PASSWORD: minha-senha
    ports:
      - "3306:3306"
    volumes:
      - ./dados-mysql:/var/lib/mysql
    networks:
      - minha-rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: meu-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge